### ISSUE TITLE
No iBOM in release

### ISSUE THREAD

**Issue by thejpster** [Neotron-Compute/Neotron-Pico#109]
Bring back the iBOM!

**Comment by jonathanpallant** [comment]
https://github.com/Neotron-Compute/Neotron-Pico/runs/7447106556?check_suite_focus=true

**Comment by jonathanpallant** [comment]
> Error: request to https://uploads.github.com/repos/Neotron-Compute/Neotron-Pico/releases/72510320/assets?name=neotron-pico-v1.0.0-rc0-ibom.html failed, reason: read ECONNRESET

**Comment by jonathanpallant** [comment]
Consider using https://github.com/ncipollo/release-action instead, as the soft props release uploader doesn't retry.
