### ISSUE TITLE
Add Schotky to VSYS input as per Datasheet

### ISSUE THREAD

**Issue by thejpster** [Neotron-Compute/Neotron-Pico#2]
https://datasheets.raspberrypi.org/pico/pico-datasheet.pdf Section 4.5

![image](https://user-images.githubusercontent.com/959887/116811088-5575b980-ab3f-11eb-9e08-3f81a5ac863b.png)

**Comment by IGBC** [comment]
if the intention of this is to switch power sources, there are better circuits that don't introduce a diode drop

**Comment by thejpster** [comment]
The intention was to not blow anything up if someone plugs the micro-USB AB port into a PC or a phone charger whilst the Neotron Pico is turned on. The Schotky drop should be about 0.4V, which at the ~100mA the Pico uses is about 40mW.

The datasheet goes on to explain that a P-channel MOSFET, such as the Diodes DMG2305UX, will do the job and drop less voltage. Would you suggest we do that, or did you have another idea?

**Comment by IGBC** [comment]
yea OK looks good to me.
